### ISSUE TITLE
Bomb Doesn't Detect Ground

### ISSUE THREAD

**Issue by Drakensin** [ErdbeerbaerLP/TaleCraft#2]
It can hit a wall, but it NoClips into the ground

**Comment by Drakensin** [comment]
Goes through Oak Trees only so far as well

**Comment by ErdbeerbaerLP** [comment]
Not fully fixed, it is still bugged but at least it does not no-clip anymore.

Thrown against Wall:
![image](https://user-images.githubusercontent.com/27149563/52566973-6ecda680-2e0b-11e9-854e-bcbf7f5b5994.png)

Thrown on ground:
![image](https://user-images.githubusercontent.com/27149563/52566990-7a20d200-2e0b-11e9-9d54-d25fb58c3178.png)

(Closing it for now)
